### Add a filter context
POST http://localhost:3000/api/v1/entities/workspaces/demo_ws/filterContexts
Authorization: Bearer YWRtaW46Ym9vdHN0cmFwOmFkbWluMTIz
Content-Type: application/vnd.gooddata.api+json

{
  "data": {
    "attributes": {
      "title": "filterContext",
      "description": "",
      "content": {
        "filters": [
          {
            "attributeFilter": {
              "displayForm": {
                "identifier": {
                  "id": "products.category",
                  "type": "label"
                }
              },
              "negativeSelection": true,
              "attributeElements": {
                "uris": []
              },
              "localIdentifier": "5b801bdbed134babbab667db74f2e7d1",
              "filterElementsBy": []
            }
          }
        ],
        "version": "2"
      }
    },
    "id": "flex_filter_context",
    "type": "filterContext"
  }
}

### Remove filter context
DELETE http://localhost:3000/api/v1/entities/workspaces/demo_ws/filterContexts
Authorization: Bearer YWRtaW46Ym9vdHN0cmFwOmFkbWluMTIz

### Add a dummy dashboard to the Tiger server
POST http://localhost:3000/api/v1/entities/workspaces/demo_ws/analyticalDashboards
Authorization: Bearer YWRtaW46Ym9vdHN0cmFwOmFkbWluMTIz
Content-Type: application/vnd.gooddata.api+json

{
  "data": {
    "attributes": {
      "title": "Simple dashboard",
      "description": "A dashboard with custom content for flex layout",
      "content": {
        "filterContextRef": {
          "identifier": {
            "id": "flex_filter_context",
            "type": "filterContext"
          }
        },
        "layout": {
          "rootWidget": "col1",
          "widgets": [
            {
              "uuid": "col1",
              "type": "column",
              "size": {
                "width": 12
              },
              "children": [
                "desc1",
                "row1",
                "desc2",
                "row2"
              ]
            },
            {
              "uuid": "row1",
              "type": "row",
              "children": [
                "ins1",
                "ins2"
              ]
            },
            {
              "uuid": "row2",
              "type": "row",
              "children": [
                "ins3",
                "ins4"
              ]
            },
            {
              "uuid": "ins1",
              "type": "insight",
              "size": {
                "width": 6,
                "height": 300
              },
              "config": {
                "insightId": "customers_trend"
              }
            },
            {
              "uuid": "ins2",
              "type": "insight",
              "size": {
                "width": 6,
                "height": 300
              },
              "config": {
                "insightId": "campaign_spend"
              }
            },
            {
              "uuid": "ins3",
              "type": "insight",
              "size": {
                "height": 300,
                "width": 6
              },
              "config": {
                "insightId": "percentage_of_customers_by_region"
              }
            },
            {
              "uuid": "ins4",
              "type": "insight",
              "size": {
                "width": 6,
                "height": 300
              },
              "config": {
                "insightId": "product_breakdown"
              }
            },
            {
              "uuid": "desc1",
              "type": "description",
              "size": {
                "width": 12
              },
              "config": {
                "title": "The first section"
              }
            },
            {
              "uuid": "desc2",
              "type": "description",
              "size": {
                "width": 12
              },
              "config": {
                "title": "Another section",
                "description": "With extra description"
              }
            }
          ]
        },
        "version": "3"
      }
    },
    "id": "simple",
    "type": "analyticalDashboard"
  }
}


### Remove the dashboard
DELETE http://localhost:3000/api/v1/entities/workspaces/demo_ws/analyticalDashboards/simple
Authorization: Bearer YWRtaW46Ym9vdHN0cmFwOmFkbWluMTIz
